- name: debug
  debug:
    msg: "jeste provisionere"


- name: try ping
  ping:
  become: True
  when: inventory_hostname != "localhost"
  register: reg_ping
  ignore_errors: True

- name: aa
  debug:
    msg: "{{reg_ping}}"

- name: try to provision
  include_tasks: "{{item}}"
  loop: "{{ lookup('fileglob', 'providers/*.yml', wantlist=True) }}"
  when: reg_ping.unreachable|default(False) or reg_ping.failed|default(False)

- meta: clear_host_errors

- name: try ping after provision
  ping:
  become: True
  when: inventory_hostname != "localhost"
